### ISSUE TITLE
Bibliography Style Question/Issue

### ISSUE THREAD

**Issue by BrunoBerger** [steinmetz/smart_city_itd_2020#1]
Hi,
I don't quite get how this is supposed to work.

https://github.com/steinmetz/smart_city_itd_2020/blob/b74b4d15ddcd8f6037eb44e0700e4c0f9cce28cf/chapters/chapter6_bruno/chapter.tex#L56-L58

Maybe I missed something that I should have done additionally, I didn't add anything, just cited something in my chapter.bib.
There is no bibliography at the end of the chapter or the book when compiling.
The citations appear as  "lorem ipsum[?]"

Am I missing something?

**Comment by steinmetz** [comment]
Hi, 
Thanks for letting me know.

Please move your .bib file to the root of the folder and rename it as your chapter, in your case chapter6.bib

Then change this line like this: \bibliography{chapter6.bib}

![image](https://user-images.githubusercontent.com/3587083/86055616-5a1f9c00-ba5c-11ea-83e6-bb8cf7938031.png)

**Comment by BrunoBerger** [comment]
Great, that fixed it, ty
